### ISSUE TITLE
Support easing between extents

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/easey-DEAD#1]

**Comment by ansis** [comment]
This should be very simple with stamen/modestmaps-js#129

Right now there are `easey.location` and `easey.point`. Should an `easey.extent` be added?
On a related note, should functions to set `from` be added for all these types?

Other possibilities include:
- overloading `easey.to` and `easey.from` to accept all the types
- only having support for coordinates. There is no need to have these convenience functions in easey since conversions are trivial.

**Comment by tmcw** [comment]
Let's keep easey minimal; coords for the win.
