### ISSUE TITLE
Finish mousewheel easing

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/easey-DEAD#6]

**Comment by mikemorris** [comment]
m.getZoom() displaying incorrect values in easey.MouseWheelHandler callback

```
  wax.tilejson(url, function(tilejson) {
    // New street-level map, centered on Washington, DC
    m = new MM.Map('map', new wax.mm.connector(tilejson), null, [
      new easey.MouseWheelHandler()
    ]);

    m.setCenterZoom({ lat: 38.8903694152832, lon: -77.0319595336914 }, 13);
    m.setZoomRange(9, 16);

    // Add zoomed event listener
    m.addCallback('zoomed', function(m) {
      console.log(m.getZoom());
    });    
  });
```

**Comment by tmcw** [comment]
Incorrect how? Can you add some more detail?

**Comment by mikemorris** [comment]
It's either firing the callback at the wrong time or reporting the wrong value (and sometimes not firing at all, or at least the console.log isn't showing up). Some variation of this behavior is also present in easy.DoubleClickHandler.

It seems to be reporting the zoom value at the end of a zoom in, but at the beginning of a zoom out. Using the sample code above, I'll scroll out until I see a zoom level reported in the console. This initial value should be correct. Then, zoom in one tick, and zoom back out one tick. The value reported for both of these zoomed events is the same. So if I initially scroll out to zoom level 9, scroll into 10, then scroll back out, it's reporting the zoom level for the last action as 10, instead of reporting that I'm back to zoom level 9.

Using Safari Version 5.1.5 (7534.55.3)
